// Package app implements the server-side logic for the Investigation Service.
package app

import (
	"context"
	"fmt"
	pb "github.com/vpapanaga/pulse-patrol/api/proto"
	"log"
)

// GRPCServer defines the object that implements the InvestigationService interface
// generated by protoc. This is what you reference as &app.GRPCServer{} in main.
type GRPCServer struct {
	// This is required for forward compatibility with gRPC
	pb.UnimplementedInvestigationServiceServer
}

// SendAlert implements the RPC method defined in investigation.proto.
// It processes incoming critical alerts from the Clinical Orchestrator.
func (s *GRPCServer) SendAlert(ctx context.Context, req *pb.AlertRequest) (*pb.AlertResponse, error) {
	// For Junior/Middle level: Log incoming data to verify the connection is working.
	log.Printf("[gRPC] Received Alert for Patient: %s | Value: %d", req.GetPatientId(), req.GetCurrentValue())

	// Logic: In a full implementation, this would save to Aurora and push to SQS (ADR #02).
	return &pb.AlertResponse{
		Status:     "SUCCESS",
		TrackingId: fmt.Sprintf("TRK-%d", req.GetCurrentValue()),
	}, nil
}
