// investigation.proto
// This file defines the gRPC service contract for the Investigation Service.
// It facilitates high-speed internal communication as required by NFR33.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/investigation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvestigationService_SendAlert_FullMethodName = "/investigation.InvestigationService/SendAlert"
)

// InvestigationServiceClient is the client API for InvestigationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InvestigationService handles internal clinical signals and alerts.
type InvestigationServiceClient interface {
	// SendAlert transmits a critical patient condition to the Clinical Orchestrator.
	// This call is designed to be low-latency to satisfy real-time monitoring needs.
	SendAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error)
}

type investigationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvestigationServiceClient(cc grpc.ClientConnInterface) InvestigationServiceClient {
	return &investigationServiceClient{cc}
}

func (c *investigationServiceClient) SendAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertResponse)
	err := c.cc.Invoke(ctx, InvestigationService_SendAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvestigationServiceServer is the server API for InvestigationService service.
// All implementations must embed UnimplementedInvestigationServiceServer
// for forward compatibility.
//
// InvestigationService handles internal clinical signals and alerts.
type InvestigationServiceServer interface {
	// SendAlert transmits a critical patient condition to the Clinical Orchestrator.
	// This call is designed to be low-latency to satisfy real-time monitoring needs.
	SendAlert(context.Context, *AlertRequest) (*AlertResponse, error)
	mustEmbedUnimplementedInvestigationServiceServer()
}

// UnimplementedInvestigationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvestigationServiceServer struct{}

func (UnimplementedInvestigationServiceServer) SendAlert(context.Context, *AlertRequest) (*AlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAlert not implemented")
}
func (UnimplementedInvestigationServiceServer) mustEmbedUnimplementedInvestigationServiceServer() {}
func (UnimplementedInvestigationServiceServer) testEmbeddedByValue()                              {}

// UnsafeInvestigationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvestigationServiceServer will
// result in compilation errors.
type UnsafeInvestigationServiceServer interface {
	mustEmbedUnimplementedInvestigationServiceServer()
}

func RegisterInvestigationServiceServer(s grpc.ServiceRegistrar, srv InvestigationServiceServer) {
	// If the following call panics, it indicates UnimplementedInvestigationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvestigationService_ServiceDesc, srv)
}

func _InvestigationService_SendAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvestigationServiceServer).SendAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvestigationService_SendAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvestigationServiceServer).SendAlert(ctx, req.(*AlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvestigationService_ServiceDesc is the grpc.ServiceDesc for InvestigationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvestigationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "investigation.InvestigationService",
	HandlerType: (*InvestigationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAlert",
			Handler:    _InvestigationService_SendAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/investigation.proto",
}
