// investigation.proto
// This file defines the gRPC service contract for the Investigation Service.
// It facilitates high-speed internal communication as required by NFR33.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/investigation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertRequest encapsulates the patient's condition and vital sign data.
type AlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`           // Unique identifier for the patient
	AlertType     string                 `protobuf:"bytes,2,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`           // Category of alert (e.g., TACHYCARDIA, BRADYCARDIA)
	CurrentValue  int32                  `protobuf:"varint,3,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"` // The actual sensor value that triggered the alert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRequest) Reset() {
	*x = AlertRequest{}
	mi := &file_api_proto_investigation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRequest) ProtoMessage() {}

func (x *AlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_investigation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRequest.ProtoReflect.Descriptor instead.
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_investigation_proto_rawDescGZIP(), []int{0}
}

func (x *AlertRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AlertRequest) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *AlertRequest) GetCurrentValue() int32 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

// AlertResponse provides confirmation of the alert processing.
type AlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                           // Status of the request (e.g., RECEIVED, PROCESSED)
	TrackingId    string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"` // Unique ID used for the Shadow Audit log (ADR #02)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertResponse) Reset() {
	*x = AlertResponse{}
	mi := &file_api_proto_investigation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertResponse) ProtoMessage() {}

func (x *AlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_investigation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertResponse.ProtoReflect.Descriptor instead.
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_investigation_proto_rawDescGZIP(), []int{1}
}

func (x *AlertResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlertResponse) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

var File_api_proto_investigation_proto protoreflect.FileDescriptor

const file_api_proto_investigation_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/investigation.proto\x12\rinvestigation\"q\n" +
	"\fAlertRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x02 \x01(\tR\talertType\x12#\n" +
	"\rcurrent_value\x18\x03 \x01(\x05R\fcurrentValue\"H\n" +
	"\rAlertResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\tR\n" +
	"trackingId2^\n" +
	"\x14InvestigationService\x12F\n" +
	"\tSendAlert\x12\x1b.investigation.AlertRequest\x1a\x1c.investigation.AlertResponseB\x18Z\x16pulse-patrol/api/protob\x06proto3"

var (
	file_api_proto_investigation_proto_rawDescOnce sync.Once
	file_api_proto_investigation_proto_rawDescData []byte
)

func file_api_proto_investigation_proto_rawDescGZIP() []byte {
	file_api_proto_investigation_proto_rawDescOnce.Do(func() {
		file_api_proto_investigation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_investigation_proto_rawDesc), len(file_api_proto_investigation_proto_rawDesc)))
	})
	return file_api_proto_investigation_proto_rawDescData
}

var file_api_proto_investigation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_investigation_proto_goTypes = []any{
	(*AlertRequest)(nil),  // 0: investigation.AlertRequest
	(*AlertResponse)(nil), // 1: investigation.AlertResponse
}
var file_api_proto_investigation_proto_depIdxs = []int32{
	0, // 0: investigation.InvestigationService.SendAlert:input_type -> investigation.AlertRequest
	1, // 1: investigation.InvestigationService.SendAlert:output_type -> investigation.AlertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_investigation_proto_init() }
func file_api_proto_investigation_proto_init() {
	if File_api_proto_investigation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_investigation_proto_rawDesc), len(file_api_proto_investigation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_investigation_proto_goTypes,
		DependencyIndexes: file_api_proto_investigation_proto_depIdxs,
		MessageInfos:      file_api_proto_investigation_proto_msgTypes,
	}.Build()
	File_api_proto_investigation_proto = out.File
	file_api_proto_investigation_proto_goTypes = nil
	file_api_proto_investigation_proto_depIdxs = nil
}
